### ISSUE TITLE
A cf-resource env variable should override the same one provided by a manifest

### ISSUE THREAD

**Issue by o-orand** [concourse/cf-resource#16]
According to [this comment] about env variable support (https://github.com/concourse/cf-resource/pull/4#issuecomment-114860307): "It now works by adding the environment variables to the manifest, before doing the cf push". I thought an env variable provided by cf-resource would override one provided by a manifest. But it isn't. 
What do you think ?

Pipeline extract

```
   put: resource-deploy-cf-webui
    params:
      manifest: manifest.yml
      environment_variables:
        API_ENDPOINT: https://my-url.com
        API_ENDPOINT2: https://my-url.com 
```

Manifest extract

```
  env: 
    API_ENDPOINT: https://api.run.pivotal.io
```

Cf env

```
User-Provided:
API_ENDPOINT: https://api.run.pivotal.io
API_ENDPOINT2: https://my-url.com
```
