### ISSUE TITLE
The Cf resource can only be used against one space.

### ISSUE THREAD

**Issue by srbry** [concourse/cf-resource#18]
At the moment if you wish to have one pipeline deploy to many cloud foundry organisations and spaces you have to configure many resources.

Could it be changed so that organisation and space are required params instead of source? That would allow to have as many resources as you have cf foundations but target as many organisations and spaces as you would like

**Comment by srbry** [comment]
You could have params overwrite source for organisation and space and have a requirement that either  source or params is set correctly to ensure backwards compatibility

**Comment by oppegard** [comment]
This is an issue for us as well. We use the GitHub Flow model and push a "review" app to CF for acceptance by the product owner (modeled after [Heroku Review Apps](https://devcenter.heroku.com/articles/github-integration-review-apps)). We create a new CF space for each PR, making it very easy to clean up afterwards (`cf delete-space -f pr-123`).

I'd like to use this resource for pushing the app, but having it locked to a CF space is a blocker.

**Comment by srbry** [comment]
@oppegard: I have created a docker image that can be used as a workaround for this functionality at the moment.

You will need to add the following to your pipelines:
```
resource_types:
- name: srbry-cf
  type: docker-image
  source:
    repository: srbry/cf-resource
    tag: latest
```

Then just make sure that when specifying resources you specify the custom resource type.
```
resources:
- name: resource-deploy-web-app
  type: srbry-cf-cf
  source:
    api: https://api.run.pivotal.io
    username: EMAIL
    password: PASSWORD
    organization: ORG
    space: SPACE
    skip_cert_check: false
```

The docker image is based on a fork of this repo as of today with the params options added, nothing else.
