### ISSUE TITLE
Custom `routes:` in manifest not honoured

### ISSUE THREAD

**Issue by camelpunch** [concourse/cf-resource#21]
I'm trying to push an app with the following manifest:

```

---
applications:
  - name: foo
    memory: 64M
    buildpack: staticfile_buildpack
    routes:
    - route: myplace.cfapps.io/v1_2_3
    - route: myother.place.com/v1_2_3
```

When `push`ing manually from my local machine, the output includes e.g.:

```
Creating route myother.place.com/v1_2_3...
OK

Binding myother.place.com/v1_2_3 to foo...
OK

Creating route myplace.cfapps.io/v1_2_3...
OK

Binding myplace.cfapps.io/v1_2_3 to foo...
OK
```

But the cf-resource only does this:

```
Creating route foo.cfapps.io...
OK
```

Names changed to protect the innocent.
