### ISSUE TITLE
Failed to have a zero downtime deploy

### ISSUE THREAD

**Issue by projekt-markthalle** [concourse/cf-resource#22]
We're providing the `current_app_name` which matches the application name in our manifest.yml. We were expecting this configuration to result in a zero-downtime-deploy based on the documentation. However, our application **did** go down during the deploy, resulting in a 404 on that route (ex: myapp.somecloudfoundry.com)

task yaml
----------------------------------------------------------------

      - put: cloud-foundry-resource
        params:
          manifest: built/manifest.yml
          current_app_name: myapp

manifest.yml
----------------------------------------------------------------

```
---
applications:
- name: myapp
  path: .
  buildpack: python_buildpack
  command: python app/application.py
```
