### ISSUE TITLE
Allow overriding of app name in manifest

### ISSUE THREAD

**Issue by nkcraddock** [concourse/cf-resource#24]
I have a need to decide, in the pipeline, what the cf app name needs to be. It would be handy to be able to override the `name` value in the `manifest.yml` from the cf-resource thusly:

``` yaml
- put: cf-resource
  inputs:
  - name: release
  params:
    new_app_name: my-app-12345
    manifest: release/manifest.yml
    path: release
```
