### ISSUE TITLE
Tail cf logs during staging when using blue/green deployment

### ISSUE THREAD

**Issue by JohannesRudolph** [concourse/cf-resource#28]
I was just bitten by not having cf logs available when using cf-resource together with blue/green deployments (specifying `params.current_app_name`). Because cf-resource deletes the staging app when staging fails, there's no way to recover these logs either. 

Proposed solution: cf-resource should connect to `cf logs current_app_name` and pipe the output to stdout until the app was successfully started.

**Comment by aeijdenberg** [comment]
Is this bug being actively worked on? We might have interest in contributing if it's not already underway.

**Comment by JohannesRudolph** [comment]
AFAIK not, so I would hugely appreciate it. I'd be happy to assist as well if there's something I can help with (e.g. review, comment or giving you a free Cloud Foundry account to test it at meshcloud.io)

**Comment by aeijdenberg** [comment]
@JohannesRudolph - if you want to try out the PR above:

```yaml
# Add to your list of resource types
resource_types:
- name: cf-resource-with-tail
  type: docker-image
  source:
    repository: govau/cf-resource
    tag: tail

# Change instances of cf-resource to cf-resource-with-tail, e.g.
resources:
- name: my-app
  type: cf-resource-with-tail
  source:
    api: https://api.system.example.com
    username: user
    password: ((password))
    organization: org
    space: space

# Add show_app_log: true
jobs:
- name: job
  plan:
  - put: my-app
    params:
      manifest: manifest.yml
      current_app_name: my-app
      show_app_log: true
```
