### ISSUE TITLE
allow setting CF_DIAL_TIMEOUT

### ISSUE THREAD

**Issue by aussielunix** [concourse/cf-resource#29]
Given Australia is as far away from PWS as is the moon,
When my Concourse in Australia tries to do a deploy to PWS in the USA
It runs out of juice during the huge round trip and times out.

When I do a manual deploy locally
I have to set the timeout with the following:
CF_DIAL_TIMEOUT=300 cf api https://api.run.pivotal.io`

Reading source code with my limited golang glasses on I am not able to clearly see if this can be done.

**Comment by chendrix** [comment]
This is something that would be a wonderful PR to accept.

If you're interested, please start by looking at our [Contributing Guide](https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md)

I've also attached this to the Help Wanted milestone.

**Comment by chris-pollard-assurity** [comment]
I have submitted a PR for this (https://github.com/concourse/cf-resource/pull/31)

**Trying out the resource**
Also if you want to test out the resulting resource from docker, it is available on dockerhub:
(https://hub.docker.com/r/chrispassurity/cf-resource/) which can be used with the following pipeline configuration (creds etc from file!):
```
---
resource_types:
- name: cf-resource-chrisp
  type: docker-image
  source:
    repository: chrispassurity/cf-resource

resources:
- name: resource-deploy-web-app
  type: cf-resource-chrisp
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true
    command_environment_variables:
      CF_COLOR: true
      CF_DIAL_TIMEOUT: 15
      CF_TRACE: true
```
