### ISSUE TITLE
Pass env variable based on pipeline resource

### ISSUE THREAD

**Issue by drnic** [concourse/cf-resource#3]
Could I pass an "app version" semver resource into an app's env variable?

**Comment by vito** [comment]
with https://github.com/concourse/cf-resource/pull/4 merged, it might be a good next step to allow something like:

```
params:
  environment_variables_from_files:
    ABC: ./path/to/a
    VERSION: ./version/number
```
