### ISSUE TITLE
CF_DOCKER_PASSWORD doesn't get set through environment-variables

### ISSUE THREAD

**Issue by r-chris** [concourse/cf-resource#44]
Hi, I'm trying to use this resource (for the first time) and ran into trouble wen trying to push docker images as shown below. My problem is that I get this error from my pipeline and can't figure out why it things I didn't provide `CF_DOCKER_PASSWORD`:

```
FAILED
No Docker password was provided. Please provide the password by setting the CF_DOCKER_PASSWORD environment variable.
error running command: exit status 1
```

```
resources:
[...]
- name: deploy-dev
  type: cf
  source:
    api: {{cf-api-endpoint}}
    username: {{cf-username-email}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-target-space}}
    skip_cert_check: false

jobs:
[...]
- name: deploy-dev
  plan:
  - get: git
    passed: [build-docker-image]
  - get: docker-registry
    passed: [push-docker-registry]
    trigger: true
  - put: deploy-dev
    params:
      manifest: git/manifest-dev-docker.yml
      environment_variables:
        CF_DOCKER_PASSWORD: {{docker-registry-password}}
        OTHER: foo
```

The manifest-dev-docker.yml file looks something like this:

```
applications:
- name: dev-docker
  docker:
    image: myregistry.com/dev:latest
    username: myusername
  memory: 512M
  instances: 1
  services:
    - dev
  env:
    OTHER: foo
```

Do I need to completely remove the `env` section from the manifest, when trying to provide them through the pipeline or where is my error here ?

**Comment by r-chris** [comment]
ok, I'm not sure how I missed this initially, but the `README.md` actually lists:

- **docker_username**: _Optional_. This is used as the username to authenticate against a protected docker registry.
- **docker_password**: _Optional_. This should be the users password when authenticating against a protected docker registry.

So, I was able to simply change the job to:

```
jobs:
[...]
- name: deploy-dev
  plan:
  - get: git
    passed: [build-docker-image]
  - get: docker-registry
    passed: [push-docker-registry]
    trigger: true
  - put: deploy-dev
    params:
      manifest: git/manifest-dev-docker.yml
      docker_username: {{docker-registry-username}}
      docker_password: {{docker-registry-password}}
      environment_variables:
        OTHER: foo
```
