### ISSUE TITLE
Accept globs as parameters

### ISSUE THREAD

**Issue by xoebus** [concourse/cf-resource#5]
Sometimes you don't know the exact filename that you are deploying (version numbers, etc.). It would be helpful if the resource resolved these globs for you. Both the application path and the manifest path should accept globs.

If more than one file matches the glob then an error should be raised.

```
- put: app
  params:
    manifest: config/manifest-*.yml
    path: other-input/app-*.jar
```
