### ISSUE TITLE
Setting "environment_variables" gives Deprecation warning

### ISSUE THREAD

**Issue by drazen-nikolic** [concourse/cf-resource#54]
I've used the configuration like this, in the Concourse `pipeline.yml`:

```
...
    - put: cf-resource
      params:
        path: my-app/*.jar
        manifest: my-app/manifest.yml
        environment_variables:
          TEST_ENV_VARIABLE: some-value
```
Everything worked fine and as expected but I got this Deprecation warning in the Concourse logs:
```
Deprecation warning: Specifying app manifest attributes at the top level is deprecated. Found: env.
Please see http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#deprecated for alternatives and other app manifest deprecations. This feature will be removed in the future.
```
I have no experience with Go language but I guess `/out/manifest.go` should be updated, that `env` part is set not on the root level. Just my assumption.
