### ISSUE TITLE
JAR output, to be used as put input

### ISSUE THREAD

**Issue by mdramos** [concourse/cf-resource#59]
How do we set the jar as an input for the deploy step?

i build the jar in a separate container, but the put step does not pick it up...

```
---
resources:
- name: app
  type: git
  source:
    uri: <URI>
    branch: master

- name: deploy-web-app
  type: cf
  source:
    api: ((cf-api))
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-organization))
    space: ((cf-space))
    skip_cert_check: true

jobs:
- name: deploy-app
  public: true
  serial: true
  plan:
  - get: app
    trigger: true
#   - task: app-tests
#     config:
#       platform: linux
#       image_resource:
#         type: docker-image
#         source: {repository: java, tag: openjdk-8-alpine}
#       inputs:
#       - name: app
#       run:
#         path: app/test-main.sh
  - task: app-build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: java, tag: openjdk-8-alpine}
      inputs:
      - name: app
      outputs:
        - name: build-output
      run:
        path: app/build-main.sh
      

  - put: deploy-web-app
    params:
      manifest: app/manifest.yml
      path: build-output/app.jar

```
