### ISSUE TITLE
Unable to use new manifests when using "current_app_name" param

### ISSUE THREAD

**Issue by ipsi** [concourse/cf-resource#62]
If I have a `put` like

```
    - put: deploy-transaction
      resource: deploy-cf
      params:
        manifest: archive/transaction/manifest.yml
        current_app_name: transaction
```

And a manifest like

```
applications:
- name: transaction
  services:
  - redis
  buildpacks:
  - java_buildpack_offline
  memory: 1024M
  path: build/libs/transaction-1.0.0.jar
```

Then when deploying we get an error like:

```
Renaming app transaction to transaction-venerable in org MY_ORG / space temp as ci-user...
OK
Deleting app transaction in org MY_ORG / space temp as ci-user...
OK
App transaction does not exist.
Renaming app transaction-venerable to transaction in org MY_ORG / space temp as ci-user...
OK
error: Error reading manifest file:
The following manifest fields cannot be used with legacy push: buildpacks


error running command: exit status 1
```

Note that this works if we remove `current_app_name`, like so:

```
    - put: deploy-transaction
      resource: deploy-cf
      params:
        manifest: archive/transaction/manifest.yml
```

**OR**

If we change `buildpacks` to `buildpack`:

```
applications:
- name: transaction
  services:
  - redis
  buildpack: java_buildpack_offline
  memory: 1024M
  path: build/libs/transaction-1.0.0.jar
```
